### ISSUE TITLE
Use of JWT instead of OAuth 1.x

### ISSUE THREAD

**Issue by bmstibbe** [GIDSOpenStandaarden/GIDS-HTI-Protocol#10]
>>Use of JWT instead of OAuth 1.x. JWT is an IETF standard and is more advanced than OAuth 1.x.

1. JWT (JSON Web Tokens) is a token format, it defines a compact and self-contained mechanism for transmitting data between parties in a way that can be verified and trusted because it is digitally signed. 
2. OAuth is an authorization protocol that use JWT
3. The OAuth specification and its extensions are being developed within the IETF OAuth Working Group.
4. LTI is based on OAuth 2.0

**Comment by JorisEdia** [comment]
Hi @bmstibbe,

I'm a bit unsure on what seems to be _the issue_. Could you please elaborate on what's wrong? When would this issue be resolved?

Thanks in advance

**Comment by rolandgroen** [comment]
LTI 1.1 makes use of OAuth 1.1, later versions use a JWT token, see also https://www.imsglobal.org/spec/lti/v1p3#json-web-token

**Comment by bmstibbe** [comment]
Ok. In the document you say that the HTI standard applies on the concepts of the IMS - Learning Tool Interoperability (LTI).
IMS defined a set of patterns (for security) that all of its specifications should use.
 
These security patterns are based upon the appropriate standards and specifications published by other organizations, like the Internet Engineering Task Force (IETF) and its Requests For Comments (RFCs).
OAuth and JWT are **_both_** being developed within the IETF OAuth Working Group.

One of the patterns in HTI is based on OpenID Connect with JWT-based message exchanges to exchanges data between a tool and the launching platform.  OpenID Connect extends OAuth 2.0 by providing user authentication and single sign-on (SSO) functionality.
