### ISSUE TITLE
intent should not link to Task-intent but https://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context.html#launch-intent

### ISSUE THREAD

**Issue by tstolker** [GIDSOpenStandaarden/GIDS-HTI-Protocol#25]
Right now, the intent claim as describes in [[FHIR value set RequestIntent](https://build.fhir.org/valueset-task-intent.html)](https://github.com/GIDSOpenStandaarden/GIDS-HTI-Protocol/blob/fhir-2-fields/HTI_2.0.md#-the-message-format) links to the [FHIR value set RequestIntent](https://build.fhir.org/valueset-task-intent.html).

This is confusing, as the intent claim is intended to specify the launch intent. 

Please link to https://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context.html#launch-intent for examples

**Comment by rolandgroen** [comment]
Will be fixed in version 2.0.0
