### ISSUE TITLE
explanation for the `exp` field in the JWT is a bit unclear

### ISSUE THREAD

**Issue by janwijbrand** [GIDSOpenStandaarden/GIDS-HTI-Protocol#6]
I read the explanation multiple times now, but I don't get it. Perhaps because it uses the word "client" - is that the portal? Perhaps an example could help here?

https://github.com/GIDSOpenStandaarden/GIDS-HTI-Protocol/blob/master/HTI.md#-the-message-format

**Comment by rolandgroen** [comment]
Updated documentation in section ② The message format with commit fe6d3c4df09e6c4eda881117deb5407e9c474dd1.
